AWSTemplateFormatVersion: 2010-09-09
Resources:
  SnsTopic:
    Type: AWS::SNS::Topic
  SnsFifoTopic:
    Type: AWS::SNS::Topic
    Properties:
      FifoTopic: true
      TopicName: MessageProcessor-SnsFifoTopic.fifo
  SqsRegularQueue:
    Type: AWS::SQS::Queue
  SqsFifoQueue:
    Type: AWS::SQS::Queue
    Properties:
      FifoQueue: true
  SnsSubscriptionRegularQueue:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: sqs
      Endpoint: !GetAtt SqsRegularQueue.Arn
      TopicArn: !Ref SnsTopic
  SnsSubscriptionFifoQueue:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: sqs
      Endpoint: !GetAtt SqsFifoQueue.Arn
      TopicArn: !Ref SnsFifoTopic
  QueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service: sns.amazonaws.com
          Action:
          - sqs:SendMessage
          Resource: '*'
          Condition:
            ArnEquals:
              aws:SourceArn: !Ref SnsTopic
      Queues:
      - !Ref SqsRegularQueue
  FifoQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service: sns.amazonaws.com
          Action:
          - sqs:SendMessage
          Resource: '*'
          Condition:
            ArnEquals:
              aws:SourceArn: !Ref SnsFifoTopic
      Queues:
      - !Ref SqsFifoQueue
  Table:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: message-processor
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: pk
          KeyType: HASH

Outputs:
  SnsTopicArn:
    Value: !Ref SnsTopic
    Export:
      Name: MessageProcessorSnsTopicArn
  SqsRegularQueueArn:
    Description: Regular Queue Arn
    Value: !GetAtt SqsRegularQueue.Arn
    Export:
      Name: MessageProcessorSqsRegularQueueArn
  SqsFifoQueueArn:
    Description: FIFO Queue Arn
    Value: !GetAtt SqsFifoQueue.Arn
    Export:
      Name: MessageProcessorSqsFifoQueueArn
